### ISSUE TITLE
Video resolution reduction when viewing streams in small windows

### ISSUE THREAD

**Issue by naicuoctavian** [aullman/opentok-meet#106]
I've noticed a video resolution reduction when the browser window viewing the (HD) video stream get's resized. 

The reduction is confirmed by the top left information panel:

* With Chrome in fullscreen I get 1280x720 @ 878kbits/s
![screen shot 2015-11-12 at 12 48 37](https://cloud.githubusercontent.com/assets/6663020/11117173/3147cbc4-8940-11e5-99a7-d16caa475e31.png)

* If I resize Chrome to take just half of the available screen real estate I get 640x360 @ 536kbits/s (the decrease in video resolution & quality is visible with the naked eye):
![screen shot 2015-11-12 at 12 48 32](https://cloud.githubusercontent.com/assets/6663020/11117187/4596fe7e-8940-11e5-9565-65e6ffb317f2.png)

The screenshots are taken while viewing the same video stream (a stream started by pressing the HD option).

Is this something inherent to the OpenTok platform or is it something implemented just by the OpenTok Meet web app? 
Can the reduction be stopped/prevented?

**Comment by aullman** [comment]
I know isn't that a great feature! :P

It's intentional. It's an experimental OpenTok feature that hasn't been released yet. The idea is that meet.tokbox.com is deciding that when you make the video element in the browser smaller than the resolution of the video then you don't need it to be that high a resolution and it requests a lower resolution in order to save bandwidth. But if you're saying the decrease in resolution is visible then this is not great. Perhaps we're not doing a great job of picking the right resolution for the size we are requesting. I'll pass this feedback on to the team.

**Comment by naicuoctavian** [comment]
So, just to confirm, this will be an (optional?) feature in OpenTok 2.6 (current version is 2.5)?

It's actually a logic and reasonable feature. 

But in the particular case that I tested today I 1st had Chrome fullscreen (1440x900) and it showed a proper HD video stream.  When I made Chrome half the width of the screen (about 720x900) the Meet web app  or OpenTok API (see my question above) decided to reduce the resolution down to a quarter of the pixels (640x360 instead of 1280x720) a change that was immediately visible to the eye since the height of the video viewing area remained the same (900px) .

**Comment by aullman** [comment]
This actually uses Simulcast (or Scalable Video which is in [beta](https://tokbox.com/platform/beta-programs/)). So it does work with one to many or many to many streaming scenarios. 

You're right though, I think we're downsizing the video too soon.

**Comment by naicuoctavian** [comment]
Thanks for the heads up.
