### ISSUE TITLE
1500 "Session.publish :: undefined" 

### ISSUE THREAD

**Issue by shabinpshams** [aullman/opentok-meet#46]
I have created .key and .crt files in the same directory.
But by creating a new room shows the error as mentioned here.
"1500 "Session.publish :: undefined" 
OT.exception :: title: Unable to Publish (1500) msg: Session.publish :: undefined 

How to solve it..?

**Comment by aullman** [comment]
@shabinpshams what was the issue?
@kenmazaika it looks like your issue is when you are trying to use screensharing. You need to create your own screensharing extension and register it with your domain. Instructions can be found at: https://tokbox.com/opentok/tutorials/screen-sharing/js/#chrome-extension

Then you will need to replace the screensharing extension ID here: https://github.com/aullman/opentok-meet/blob/master/public/js/controllers.js#L70
